remote_theme: nimiq/doc-theme
title: "Nimiq"
description: "Ecosystem"
submodule_section: "Details"
exclude: ["node_modules/*", "./*/*/**", "meta/doc-theme/libraries/**", "meta/email-template/**"]
submodules: "brief"

