remote_theme: nimiq/doc-theme
title: "Nimiq"
description: "Ecosystem"

submodule_section: "Details"
submodules: "detailed"

exclude: ["node_modules/*", "./*/*/**", "_dev/*", "meta/doc-theme/libraries/**", "meta/email-template/**"]

